[package]
name = "faceauth-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
faceauth-engine = { version = "0.1.0", path = "../faceauth-engine" }
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
